## A TALE OF TWO COVID PERIODS

In [175]:
#Import the necessary libraries
from pyecharts.charts import Map,Geo,Page
from pyecharts import options as opts 
from pyecharts.globals import ThemeType
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [4]:
#Read the data into Python's memory
covid_data1=pd.read_csv('owid-covid-data.csv')

In [5]:
#Convert the date column to date format expressly
covid_data1['date']=pd.to_datetime(covid_data1['date'])

In [6]:
#Check the first few rows of the data 
covid_data1.head()

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,...,gdp_per_capita,extreme_poverty,cardiovasc_death_rate,diabetes_prevalence,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index
0,ABW,North America,Aruba,2020-03-13,2.0,2.0,NaN,NaN,0.0,NaN,...,35973.781,NaN,NaN,11.62,NaN,NaN,NaN,NaN,76.29,NaN
1,ABW,North America,Aruba,2020-03-19,NaN,NaN,0.286,NaN,NaN,0.0,...,35973.781,NaN,NaN,11.62,NaN,NaN,NaN,NaN,76.29,NaN
2,ABW,North America,Aruba,2020-03-20,4.0,2.0,0.286,NaN,0.0,0.0,...,35973.781,NaN,NaN,11.62,NaN,NaN,NaN,NaN,76.29,NaN
3,ABW,North America,Aruba,2020-03-21,NaN,NaN,0.286,NaN,NaN,0.0,...,35973.781,NaN,NaN,11.62,NaN,NaN,NaN,NaN,76.29,NaN
4,ABW,North America,Aruba,2020-03-22,NaN,NaN,0.286,NaN,NaN,0.0,...,35973.781,NaN,NaN,11.62,NaN,NaN,NaN,NaN,76.29,NaN

In [7]:
#Filter out rows in which the total cases are missing
df=covid_data1[covid_data1['total_cases']!='']

In [8]:
df.head()

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,...,gdp_per_capita,extreme_poverty,cardiovasc_death_rate,diabetes_prevalence,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index
0,ABW,North America,Aruba,2020-03-13,2.0,2.0,NaN,NaN,0.0,NaN,...,35973.781,NaN,NaN,11.62,NaN,NaN,NaN,NaN,76.29,NaN
1,ABW,North America,Aruba,2020-03-19,NaN,NaN,0.286,NaN,NaN,0.0,...,35973.781,NaN,NaN,11.62,NaN,NaN,NaN,NaN,76.29,NaN
2,ABW,North America,Aruba,2020-03-20,4.0,2.0,0.286,NaN,0.0,0.0,...,35973.781,NaN,NaN,11.62,NaN,NaN,NaN,NaN,76.29,NaN
3,ABW,North America,Aruba,2020-03-21,NaN,NaN,0.286,NaN,NaN,0.0,...,35973.781,NaN,NaN,11.62,NaN,NaN,NaN,NaN,76.29,NaN
4,ABW,North America,Aruba,2020-03-22,NaN,NaN,0.286,NaN,NaN,0.0,...,35973.781,NaN,NaN,11.62,NaN,NaN,NaN,NaN,76.29,NaN

In [120]:
#Sort the data by date
df=covid_data1.sort_values(by=['date'],ascending=False)

In [121]:
#Get the data for the the date we are interested in
df_for_map=df[df['date']=='2020-06-01']

In [122]:
#Reset the index
df_for_map.reset_index(drop=True,inplace=True)

In [123]:
#Check the first few rows of the data needed for our work
df_for_map.head()

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,...,gdp_per_capita,extreme_poverty,cardiovasc_death_rate,diabetes_prevalence,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index
0,JOR,Asia,Jordan,2020-06-01,739.0,5.0,4.429,9.0,0.0,0.000,...,8337.490,0.1,208.257,11.75,NaN,NaN,NaN,1.40,74.53,0.735
1,UZB,Asia,Uzbekistan,2020-06-01,3662.0,108.0,71.143,15.0,1.0,0.286,...,6253.104,NaN,724.417,7.57,1.3,24.7,NaN,4.00,71.72,0.710
2,SVK,Europe,Slovakia,2020-06-01,1522.0,1.0,1.857,28.0,0.0,0.000,...,30155.152,0.7,287.959,7.29,23.1,37.7,NaN,5.82,77.54,0.855
3,LCA,North America,Saint Lucia,2020-06-01,18.0,0.0,0.000,NaN,0.0,0.000,...,12951.839,NaN,204.620,11.62,NaN,NaN,87.202,1.30,76.20,0.747
4,AGO,Africa,Angola,2020-06-01,86.0,2.0,2.429,4.0,0.0,0.000,...,5819.495,NaN,276.045,3.94,NaN,NaN,26.664,NaN,61.15,0.581

In [124]:
#Create two data series required for data visualization
country=(df_for_map['location'])
totalcases=list(df_for_map['total_cases'])

In [125]:
#prepare the data for visualization
list1=[[country[i],totalcases[i]] for i in range (len(country))]

In [126]:
#Create the map and set the size of the map
map1=Map(init_opts=opts.InitOpts(width="1000px",height="460px",theme=ThemeType.ROMANTIC))

C:\Users\MY PC\New folder\lib\site-packages\pyecharts\charts\chart.py:14: PendingDeprecationWarning: pyecharts 所有图表类型将在 v1.9.0 版本开始强制使用 ChartItem 进行数据项配置 :)
  super().__init__(init_opts=init_opts)

In [127]:
#Add world map
map1.add("Total confirmed cases", list1,maptype="world",is_map_symbol_show=False);

In [128]:
# Set global configuration
#Change the legend from a sliding bar to the color bins by tweaking the VisualMapOpts parameter
#Add title and subtitle to the chart
map1.set_global_opts(visualmap_opts=opts.VisualMapOpts(max_=1100000,
                                                       is_piecewise=True,
                                                       pieces=[{
                                                           "min": 500000
                                                       }, {
                                                           "min": 100000,"max":199999
                                                       },{"min":50000,"max":99999},{"min":10000,"max":49999},{"max":9999},]),
                     legend_opts=opts.LegendOpts(is_show=False),title_opts=opts.TitleOpts(title="Covid-19 Worldwide Total Cases",subtitle='Cases as at 1st June 2020',pos_left='center',padding=0,item_gap=2,title_textstyle_opts=opts.TextStyleOpts(color='darkblue',font_weight='bold',font_family='Courier New',font_size=30),subtitle_textstyle_opts=opts.TextStyleOpts
                                                                                         (color='green',font_weight='bold',font_family='Courier New',font_size=15)));

In [129]:
#Remove country name serving as label
map1.set_series_opts(label_opts=opts.LabelOpts(is_show=False));

In [157]:
#save the map as an html file
#map1.render('covid-worldwide-total-cases-1st-JUNE.html')
#Render the map inside the notebook
map1.render_notebook()

In [131]:
#Read the data into memory
covid_data2=pd.read_csv('owid-covid-data-update-to-DEC.csv')

In [132]:
#Convert the date column to date format expressly
covid_data1['date']=pd.to_datetime(covid_data1['date'])

In [133]:
#Filter out rows in which the total cases are missing
df2=covid_data2[covid_data2['total_cases']!='']

In [134]:
#Sort the data by date
df2=covid_data2.sort_values(by=['date'],ascending=False)

In [135]:
#Get the data for the the date we are interested in
df_for_map2=df2[df2['date']=='2020-12-21']

In [136]:
#Reset the index
df_for_map2.reset_index(drop=True,inplace=True)

In [138]:
#Check the first few rows of the data needed for our work
df_for_map2.head()

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,...,gdp_per_capita,extreme_poverty,cardiovasc_death_rate,diabetes_prevalence,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index
0,ZWE,Africa,Zimbabwe,2020-12-21,12422.0,97.0,152.000,322.0,2.0,1.857,...,1899.775,21.4,307.846,1.82,1.6,30.7,36.791,1.70,61.49,0.535
1,CHN,Asia,China,2020-12-21,95150.0,100.0,103.286,4765.0,1.0,1.571,...,15308.712,0.7,261.899,9.74,1.9,48.4,NaN,4.34,76.91,0.752
2,NIC,North America,Nicaragua,2020-12-21,5938.0,0.0,7.286,163.0,0.0,0.143,...,5321.444,3.2,137.016,11.47,NaN,NaN,NaN,0.90,74.48,0.658
3,NZL,Oceania,New Zealand,2020-12-21,2121.0,0.0,3.571,25.0,0.0,0.000,...,36085.843,NaN,128.797,8.08,14.8,17.2,NaN,2.61,82.29,0.917
4,USA,North America,United States,2020-12-21,18035209.0,190519.0,215428.857,319364.0,1696.0,2655.286,...,54225.446,1.2,151.089,10.79,19.1,24.6,NaN,2.77,78.86,0.924

In [139]:
#Create two data series required for data visualization
country2=(df_for_map2['location'])
totalcases2=list(df_for_map2['total_cases'])

In [140]:
#prepare the data for visualization
list2=[[country2[i],totalcases2[i]] for i in range (len(country2))]

In [141]:
#Create the map and set the size of the map
map2=Map(init_opts=opts.InitOpts(width="1000px",height="460px",theme=ThemeType.VINTAGE));

C:\Users\MY PC\New folder\lib\site-packages\pyecharts\charts\chart.py:14: PendingDeprecationWarning: pyecharts 所有图表类型将在 v1.9.0 版本开始强制使用 ChartItem 进行数据项配置 :)
  super().__init__(init_opts=init_opts)

In [142]:
#Add world map
map2.add("Total confirmed cases", list2,maptype="world",is_map_symbol_show=False);

In [143]:
# Set global configuration
#Change the legend from a sliding bar to the color bins by tweaking the VisualMapOpts parameter
#Add title and subtitle to the chart
map2.set_global_opts(visualmap_opts=opts.VisualMapOpts(max_=1100000,
                                                       is_piecewise=True,
                                                       pieces=[{
                                                           "min": 500000
                                                       }, {
                                                           "min": 100000,"max":199999
                                                       },{"min":50000,"max":99999},{"min":10000,"max":49999},{"max":9999},]),
                     legend_opts=opts.LegendOpts(is_show=False),title_opts=opts.TitleOpts(title="Covid-19 Worldwide Total Cases",subtitle='Cases as at 21st December 2020',pos_left='center',padding=0,item_gap=2,title_textstyle_opts=opts.TextStyleOpts(color='darkblue',font_weight='bold',font_family='Courier New',font_size=30),subtitle_textstyle_opts=opts.TextStyleOpts
                                                                                         (color='green',font_weight='bold',font_family='Courier New',font_size=15)));

In [144]:
#Remove country name serving as label
map2.set_series_opts(label_opts=opts.LabelOpts(is_show=False));

In [176]:
#save the map as an html file
#map2.render('covid-worldwide-total-cases-21st-DEC.html')
#Render the map inside the notebook
map2.render_notebook()

In [180]:
#It is possible to display the two charts all at once using the page submodule of the Pyechart library
Page=Page()

In [181]:
#Bring the two charts together
Page.add(map1,map2)

In [183]:
#Save the otuput 
#Render the output in the notebook
Page.render('doubletotalcase.html')
Page.render_notebook()